service: register-company-service

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:*:table/CompanyTable
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - arn:aws:sqs:${aws:region}:*:CompanyDLQ

functions:
  register:
    handler: lambda/company-registration.handler
    events:
      - http:
          path: register
          method: post
    maximumRetryAttempts: 2

resources:
  Resources:
    CompanyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CompanyTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: cuit
            AttributeType: S
        KeySchema:
          - AttributeName: cuit
            KeyType: HASH

    CompanyDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: CompanyDLQ

plugins:
  - serverless-offline
