service: interbanking-company-registration

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

functions:
  registerCompany:
    handler: lambda/company-registration.handler
    events:
      - httpApi:
          path: /companies
          method: post

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - 'lambda/**'
    - '!src/**'

plugins:
  - serverless-offline

custom:
  esbuild:
    bundle: true
    target: node20
    format: esm
    platform: node
    tsconfig: tsconfig.lambda.json
    outdir: .serverless
